#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $color;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
$full_text = "";
$color = "";

binmode STDIN, ":encoding(UTF-8)";

if ($percent <= 25) {
  $full_text = "\x{f243}\n";  # fontawesome fa-battery-quarter
  $short_text = "\x{f243}\n"; # fontawesome fa-battery-quarter

  if ($status eq 'Discharging') {
    $color = "#F44336\n";     # red 500
  } else {
    $color = "#8BC34A\n";     # light green 500
  }
} elsif ($percent <= 50) {
  $full_text = "\x{f242}\n";  # fontawesome fa-battery-half
  $short_text = "\x{f242}\n"; # fontawesome fa-battery-half

  if ($status eq 'Discharging') {
    $color = "#FF9800\n";     # orange 500
  } else {
    $color = "#8BC34A\n";     # light green 500
  }
} elsif ($percent <= 75) {
  $full_text = "\x{f241}\n";  # fontawesome fa-battery-three-quarters
  $short_text = "\x{f241}\n"; # fontawesome fa-battery-three-quarters

  if ($status eq 'Discharging') {
    $color = "#FFEB3B\n";     # yellow 500
  } else {
    $color = "#8BC34A\n";     # light green 500
  }
} else {
  $full_text = "\x{f240}\n";  # fontawesome fa-battery-full
  $short_text = "\x{f240}\n"; # fontawesome fa-battery-full

  if ($status eq 'Discharging') {
    $color = "#BDBDBD\n";     # grey 400
  } else {
    $color = "#8BC34A\n";     # light green 500
  }
}

print $full_text;
print $short_text;
print $color;

if ($percent < 5) {
  exit(33);
}

exit(0);
