#!/bin/bash

device="${BLOCK_INSTANCE:-ens3f1}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "${quality}%"
    echo "${quality}%"
    echo "OFF"

    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    # fontawesome 4.6.3
    # exchange
    echo "  ON"
    echo "  ON"
    echo \#8BC34A
  fi
fi
